name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install swift
      uses: YOCKOW/Action-setup-swift@v1
      with:
        swift-version: "5.4.1"

    - name: Run tests
      run: swift test --enable-test-discovery
